[project]
name = "weather"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
<<<<<<< HEAD
    "pandas>=2.2.3",
=======
>>>>>>> 0ee0d17 (Initial implementation of UV server for weather app)
]
